name: Host Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sivakov512/llvm:19

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: tests/host/build
          key: ${{ runner.os }}-host-checks-${{ hashFiles('tests/host/CMakeLists.txt', 'components/**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-host-checks-

      - name: Run tests
        run: make host-test

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sivakov512/llvm:19

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            tests/host/.cache
            tests/host/build
          key: ${{ runner.os }}-host-checks-${{ hashFiles('tests/host/CMakeLists.txt', 'components/**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-host-checks-

      - name: Run static analysis
        run: make host-lint
