name: Formatting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sivakov512/llvm:19

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code formatting
        run: make check-format
