name: Libs test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: libs/unity/build
          key: ${{ runner.os }}-cmake-${{ hashFiles('libs/unity/CMakeLists.txt', 'libs/*/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Run tests
        run: make libs-test
